---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Test variables
      debug:
        msg:
          - "CLIENT={{ client_name | default('Firma_Kowalski') }}"
          - "IP={{ client_ip | default('10.100.1.2') }}"
          - "LAN={{ client_lan | default('10.0.0.0/24') }}"
          - "Semaphore działa"
