---
- hosts: localhost
  gather_facts: false

  vars:
    client_name: "{{ client_name | default('test_client') }}"
    client_ip: "{{ client_ip | default('10.100.1.2') }}"
    client_lan: "{{ client_lan | default('10.0.0.0/24') }}"

  tasks:
    - name: Generate private key
      shell: wg genkey
      register: privatekey

    - name: Generate public key
      shell: echo "{{ privatekey.stdout }}" | wg pubkey
      register: publickey

    - name: Show WireGuard client configuration
      debug:
        msg:
          - "CLIENT={{ client_name }}"
          - "IP={{ client_ip }}"
          - "LAN={{ client_lan }}"
          - "PRIVATE={{ privatekey.stdout }}"
          - "PUBLIC={{ publickey.stdout }}"
