---
- hosts: localhost
  gather_facts: no

---
- hosts: localhost
  gather_facts: false

  vars:
    client_name: "{{ client_name }}"
    client_ip: "{{ client_ip }}"
    client_lan: "{{ client_lan }}"

  tasks:

    - name: Generate private key
      shell: wg genkey
      register: privatekey

    - name: Generate public key
      shell: echo "{{ privatekey.stdout }}" | wg pubkey
      register: publickey

    - name: Show configuration
      debug:
        msg:
          - "CLIENT={{ client_name }}"
          - "IP={{ client_ip }}"
          - "LAN={{ client_lan }}"
          - "PRIVATE={{ privatekey.stdout }}"
          - "PUBLIC={{ publickey.stdout }}"
  tasks:
    - name: Test AWX
      debug:
        msg: "AWX działa poprawnie"
